package entity;
// Generated 13/06/2021 02:31:36 AM by Hibernate Tools 4.3.1



/**
 * Ejercicios generated by hbm2java
 */
public class Ejercicios  implements java.io.Serializable {


     private Integer id;
     private String columnajson;

    public Ejercicios() {
    }

    public Ejercicios(String columnajson) {
       this.columnajson = columnajson;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getColumnajson() {
        return this.columnajson;
    }
    
    public void setColumnajson(String columnajson) {
        this.columnajson = columnajson;
    }




}


