package entity;
// Generated 13/06/2021 02:31:36 AM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String usuario;
     private String contra;

    public Usuarios() {
    }

	
    public Usuarios(String usuario) {
        this.usuario = usuario;
    }
    public Usuarios(String usuario, String contra) {
       this.usuario = usuario;
       this.contra = contra;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContra() {
        return this.contra;
    }
    
    public void setContra(String contra) {
        this.contra = contra;
    }




}


